jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Start ZAP Proxy
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2_13_0_unix.sh
          chmod +x ZAP_2_13_0_unix.sh
          ./ZAP_2_13_0_unix.sh -daemon -host 0.0.0.0 -port 8080
        background: true

      - name: Wait for ZAP to start
        run: |
          for i in {1..30}; do
            if nc -z localhost 8080; then
              echo "ZAP is running"
              break
            fi
            echo "Waiting for ZAP to start..."
            sleep 2
          done

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set environment variables
        run: echo "ZAP_API_KEY=${{ secrets.ZAP_API_KEY }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test